version: 2.1
jobs:
#  build:
#    docker:
#      - image: circleci/golang:1.9
#    working_directory: /go/src/github.com/mgkanani/gls
#    steps:
#      - checkout

      # specify any bash command here prefixed with `run: `
#      - run: go get -v -t -d ./...
#      - run: go test -v ./...
#      - run: go test -bench -v ./...
  test:
    working_directory: /go/src/github.com/mgkanani/gls
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: run test
          command: |
            go get -v -t -d ./...
            go get github.com/mattn/goveralls
            go test -v -cover -coverprofile=coverage.out
            $GOPATH/bin/goveralls -coverprofile=coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN

workflows:
  version: 2.1
  test:
    jobs:
#      - build
      - test

notify:
 webhooks:
   - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}
